function dataFrame = createBlankDataFrame()

%Creates a blank data frame

dataFrame = struct('numNPCs_d0', 0, ...
        'numCortA_d0', 0, ...
        'numDeltaA_d0', 0, ...
        'numEfnA_d0', 0, ...
        'numWntA_d0', 0, ...
        'flDeltaA_d0', 0, ...
        'flEfnA_d0', 0, ...
        'flWntA_d0', 0, ...
        'numNPCs_d6', 0, ...
        'numCortA_d6', 0, ...
        'numDeltaA_d6', 0, ...
        'numEfnA_d6', 0, ...
        'numWntA_d6', 0, ...
        'numTuj1', 0, ...
        'numGFAP', 0, ...
        'numDbl', 0, ...
        'numUnst', 0);
